// <auto-generated />
using System;
using GestorMEI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorMEI.Data.Migrations
{
    [DbContext(typeof(MeiContext))]
    [Migration("20250411013355_MEI-DB")]
    partial class MEIDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorMEI.Data.Model.AssinaturaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataFim");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInicio");

                    b.Property<Guid>("IdTGStatusAssinatura")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGStatusAssinatura");

                    b.Property<Guid>("IdTGTipoAssinatura")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGTipoAssinatura");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("IdTGStatusAssinatura");

                    b.HasIndex("IdTGTipoAssinatura");

                    b.ToTable("Assinatura");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.EmpresaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("CEP");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cidade");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("Complemento");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Endereco");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("Estado");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NomeFantasia");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("Numero");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RazaoSocial");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Telefone");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.TabelaGeralItemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("Sigla");

                    b.Property<Guid>("TabelaGeralId")
                        .HasColumnType("uuid")
                        .HasColumnName("TabelaGeralId");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.HasIndex("TabelaGeralId");

                    b.ToTable("TabelaGeralItem");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.TabelaGeralModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.HasKey("Id");

                    b.ToTable("TabelaGeral");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.VendaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("ComNF")
                        .HasColumnType("boolean")
                        .HasColumnName("ComNF");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataAlteracao");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DataInclusao");

                    b.Property<DateOnly>("DataVenda")
                        .HasColumnType("date")
                        .HasColumnName("DataVenda");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("EmpresaId");

                    b.Property<Guid>("IdTGTipoVenda")
                        .HasColumnType("uuid")
                        .HasColumnName("IdTGTipoVenda");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("text")
                        .HasColumnName("UsuarioAlteracao");

                    b.Property<string>("UsuarioInclusao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UsuarioInclusao");

                    b.Property<float>("ValorVenda")
                        .HasColumnType("real")
                        .HasColumnName("ValorVenda");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("IdTGTipoVenda");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.AssinaturaModel", b =>
                {
                    b.HasOne("GestorMEI.Data.Model.TabelaGeralItemModel", "StatusAssinatura")
                        .WithMany()
                        .HasForeignKey("IdTGStatusAssinatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorMEI.Data.Model.TabelaGeralItemModel", "TipoAssinatura")
                        .WithMany()
                        .HasForeignKey("IdTGTipoAssinatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusAssinatura");

                    b.Navigation("TipoAssinatura");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.TabelaGeralItemModel", b =>
                {
                    b.HasOne("GestorMEI.Data.Model.TabelaGeralModel", "TabelaGeral")
                        .WithMany()
                        .HasForeignKey("TabelaGeralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaGeral");
                });

            modelBuilder.Entity("GestorMEI.Data.Model.VendaModel", b =>
                {
                    b.HasOne("GestorMEI.Data.Model.EmpresaModel", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorMEI.Data.Model.TabelaGeralItemModel", "TipoVenda")
                        .WithMany()
                        .HasForeignKey("IdTGTipoVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TipoVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
